# Generated by Django 4.2.1 on 2023-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_theme_indicator_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="Date",
            field=models.DateField(null=True),
        ),
    ]
