# Generated by Django 4.2.1 on 2023-06-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_indicator_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_name", models.CharField(max_length=255)),
                ("hdx_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("notes", models.CharField(max_length=255)),
                ("dataset_source", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("dataset_date_range", models.CharField(max_length=50)),
                ("last_modified", models.DateTimeField()),
                ("data_update_frequency", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="indicator",
            name="MetaData",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.metadata",
            ),
        ),
    ]
